general: 
  parameters:
    S3Bucket: aws-quickstart-urbanio-2
    ReadCapacityUnits: 5
    WriteCapacityUnits: 5
    OtherAccountNumber: 450305284055

  # s3_bucket: aws-quickstart-urbanio-ricochet-sitewise-ap-southeast-1
  # s3_bucket: aws-quickstart-urbanio-ricochet-sitewise-ap-southeast-2
  # s3_bucket: aws-quickstart-urbanio-ricochet-sitewise-eu-central-1
  # s3_bucket: aws-quickstart-urbanio-ricochet-sitewise-us-east-1
  # s3_bucket: aws-quickstart-urbanio-ricochet-sitewise-us-west-2
  # s3_bucket: aws-quickstart-urbanio-ricochet-sitewise-eu-west-1

project:
  name: aws-quickstart-urbanio
  owner: quickstart@amazon.com
  build_submodules: false
# lambda_source_path:  src
# lambda_zip_path: functions/packages
  package_lambda: false
  shorten_stack_name: true
  regions:
  - ap-southeast-1
  - ap-southeast-2
  - us-east-1
  - us-west-2
  - eu-west-1
  - eu-central-1
  # s3_bucket: aws-quickstart-urbanio-ricochet-sitewise-ap-southeast-1
  # s3_bucket: aws-quickstart-urbanio-ricochet-sitewise-ap-southeast-2
  # s3_bucket: aws-quickstart-urbanio-ricochet-sitewise-eu-central-1
  # s3_bucket: aws-quickstart-urbanio-ricochet-sitewise-us-east-1
  # s3_bucket: aws-quickstart-urbanio-ricochet-sitewise-us-west-2
  # s3_bucket: aws-quickstart-urbanio-ricochet-sitewise-eu-west-1
  s3_enable_sig_v2: true
  s3_object_acl: public-read
  template: ./templates/lambda-sqs.template.yaml
tests:
  default:
    template: ./templates/lambda-sqs.template.yaml
  # default:
  #   template: ./templates/packaged.yaml