general:
  s3_regional_buckets: true
  # s3_bucket: aws-quickstart-urbanio-ricochet-sitewise-stage
  # s3_bucket: aws-quickstart-urbanio-ricochet-sitewise-test
  s3_bucket: aws-quickstart-urbanio-ricochet-sitewise
  # parameters:
  #   OverridenVar: set_in_override

project:
  template: ./templates/packaged.yaml
  name: aws-quickstart-urbanio
  owner: quickstart@amazon.com
  build_submodules: false
  auth:
    default: urban-dev-profile
    # default: default
    # default: urban-stage-profile
    default: urban-production-profile
  lambda_source_path:  src
  lambda_zip_path: functions/packages
  package_lambda: false
  shorten_stack_name: true
  regions:
  - ap-southeast-1
  - ap-southeast-2
  - us-east-1
  - us-west-2
  - eu-west-1
  - eu-central-1
  s3_enable_sig_v2: true
  s3_object_acl: public-read
  # parameters:
  #   EnvType: test
  #   OverridenVar: set_in_project

tests:
  default:
    parameters:
      EnvType: test
      # OverridenVar: set_in_project
    tags:
      TEST_PROFILE: DEFAULT

  dev:
    template: ./templates/lambda-sqs.template.yaml
    regions:
    - ap-southeast-2
    parameters:
      EnvType: test
      S3Bucket: urbanio-sitewise
      # OverridenVar: set_in_project
    tags:
      TEST_PROFILE: TEST

  staging:
    template: ./templates/packaged.yaml
    regions:
    - ap-southeast-2
    parameters:
      EnvType: staging
      # OverridenVar: set_in_project
    tags:
      TEST_PROFILE: STAGING