general:
  s3_regional_buckets: true

project:
  template: ./templates/main.template.yaml
  name: quickstart-urbanio-iot-aas
  owner: quickstart@amazon.com
  build_submodules: false
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  package_lambda: false
  shorten_stack_name: true
  regions:
  - ap-southeast-1
  - ap-southeast-2
  - us-east-1
  - us-east-2
  - us-west-2
  - eu-west-1
  - eu-central-1
  s3_bucket: ''

tests:
  dev:
    template: ./templates/main.template.yaml
    regions:
    - ap-southeast-2
    parameters:
      EnvType: production
      S3Bucket: $[taskcat_autobucket]-set
      EmailAddress: test@example.com
      AllowCrossAccountAccess: 'false'
      UrbanioAccountNumber: '1234567890'
  
  # prod:
  #   template: ./templates/main.template.yaml
  #   regions:
  #   - ap-southeast-2
  #   parameters:
  #     EnvType: production
  #     S3Bucket: sshvans-urbanio1
  #     EmailAddress: test@example.com
  #     AllowCrossAccountAccess: 'true'
  #     UrbanioAccountNumber: OVERRIDE