general:
  s3_regional_buckets: true

project:
  name: quickstart-urbanio-iot-aas
  owner: quickstart@amazon.com
  build_submodules: false
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  package_lambda: false
  shorten_stack_name: true
  regions:
  - ap-southeast-1
  - ap-southeast-2
  - us-east-1
  - us-east-2
  - us-west-2
  - eu-west-1
  - eu-central-1
  parameters:
    QSS3BucketName: $[taskcat_autobucket]

tests:
  dev:
    template: ./templates/main.template.yaml
    regions:
    - ap-southeast-1
    parameters:
      S3Bucket: $[taskcat_random-string]
      EmailAddress: test@example.com
      AllowCrossAccountAccess: 'false'
      UrbanioAccountNumber: '1234567890'
      